models:
  - name: fact_reviews
    description: "Fact table for review information"
    columns:
      - name: review_id
        description: "Primary key"
        tests:
          - not_null
          - unique