name: DBT CI

on:
  push:
    branches: [main]

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/31215446924/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'dbt-service-account@keen-genius-463512-d0.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Write BigQuery service account key to a file
        run: |
          echo "${{ secrets.BIGQUERY_KEY }}" | base64 -d > bigquery-key.json

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          dbt_project:
            target: dev
            outputs:
              dev:
                type: bigquery
                project: keen-genius-463512-d0
                dataset: dbt_staging
                threads: 2
                method: oauth
          EOF

      - name: Run dbt commands
        run: |
          dbt deps
          dbt run
          dbt test
